version: 2
jobs:
    build:
        docker:
          - image: circleci/node:lts
        steps:
          - run: echo "Build."
    test:
        docker:
          - image: circleci/node:lts
        steps:
          - run: yarn test:coveralls
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test
