version: 2
jobs:
    build:
        docker:
          - image: circleci/node:lts
        steps:
          - add_ssh_keys
          - checkout
    test:
        docker:
          - image: circleci/node:lts
        steps:
          - add_ssh_keys
          - checkout
          - run: yarn test:coveralls
